# Generated by Django 5.1.7 on 2025-03-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbotweb', '0006_exchangegoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencybalance',
            name='usd_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
